### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by Kadah** [JasXSL/SL-XOBJ#1]
Was going to the documentation to see about using it for my maze/dungeon generator, but ran in to a few issues. The runMethod() call in remove() is missing an argument.

I found this when I stepped around the unresolved "BFL&BFL_INIT" define in the root example readme by commenting out the control event.

I'm sure I'm doing some stuff wrong. An example object would be really nice, which I will bug Toonie for next time I see her.

**Comment by JasXSL** [comment]
Are you including _ROOT.lsl in your project-specific _core.lsl file? _ROOT.lsl is just a part of the framework. If you are referring to the root example script, it seems to have been fixed already.

**Comment by Kadah** [comment]
Yeah, Tonnie fixed that.

Found another compile error in "creating a module.txt", the button list pasted to Dialog$spawn needs to be escaped in parentheses or the preproc throws a "too many prams" error. I would just fix the preproc instead, but don't have the time to be distracted on that right now. (and if there was anything I was going to fix with the preproc, it would be preproc non-visible error bug)

**Comment by Kadah** [comment]
I have a feeling that in the "creating a module.txt" example the include  for _CLASS_STATIC should be in myFirstProject/classes/st Main.lsl instead of the first objects st Main script as instructed because later on the second object's st Main script cannot function without _CLASS_STATIC.

With these last two changes, the example seems to work as intended.

**Comment by JasXSL** [comment]
It was meant to include _core.lsl and _CLASS_STATIC.lsl but in all fairness I think _CLASS_STATIC.lsl in theory could be included in _ROOT.lsl since it's needed for _CLASS_PACKAGE.lsl anyways

**Comment by Kadah** [comment]
Ah, make sense. And I just found why I couldn't get a callback at the 2nd object, it needed _LISTEN.lsl. I was driving myself crazy last night trying to figure that out.

I think I got enough worked out now to start adding standard coms to my map gen and get the parts glued together. :3

**Comment by Kadah** [comment]
Was going to file this as a new issue, but looking in to it further it seems more like an outdated comment.
cl SharedVars says has conflicting info on events it raises. I was attempting to use evt$eventIsSharedScriptChange, but evt$SHARED_CHANGED is not defined and never used. My guess is that SharedVarsEvt$changed had replaced that.
