### ISSUE TITLE
Not detecting the file

### ISSUE THREAD

**Issue by Khalhys** [JasXSL/SL-XOBJ#4]
For some strange reason, the file for the download isn't being detected, even though I enabled the script to detect it:

![evidence_1](https://cloud.githubusercontent.com/assets/19635025/16390579/7e02d5dc-3c71-11e6-9104-68039efd1e05.png)
![evidence_2](https://cloud.githubusercontent.com/assets/19635025/16390587/838f062e-3c71-11e6-95e3-c31a3445060f.png)

The above shows evidence of what happened, as well as my issue at hand. Is there anything I did wrong in the process?

Thank you in advance.

**Comment by JasXSL** [comment]
What do your script settings look like?

**Comment by without-ordinary** [comment]
You're missing a closing double quote on your include.
