### ISSUE TITLE
Alpha masking seems to cause worst FPS than simple alpha toggle

### ISSUE THREAD

**Issue by without-ordinary** [JasXSL/SL-XOBJ#8]
I'll preface this, all of this has only been tested on one system so far. Further testing is necessary.

When the changing animation, the Volume VB updates when the masks are changed causes large frame time spikes. Overall, I can only replicate a FPS drop on transparent meshes with a stupid large number of invisible meshes, and this seems to be mostly caused by materials.

I've also tested using a runtime toggleable option of the current BUG-20168 patch to skip rendering full alpha faces with no noticeable effect. That code has no effect on materials though, so it's possible the face skipping is in the wrong place in the render pipeline.

Test setup:
A sit prim that fixes the camera facing a test area, player avatar is position out of frame.
With in the test area, 6-9 Thomas Losko are rezed and setup to play the attack animation on a random timer.
Fast timers and Statistics console are left open and monitored.
Thomas's jas MaskAnim is recompiled/replaced from using masks to alpha toggle.
Observe change.

**Comment by JasXSL** [comment]
Have you done any more testing with this? I really need a better system.

**Comment by JasXSL** [comment]
I'm just gonna close this since we've had animesh for like 5 years now.
